### ISSUE TITLE
Kinds of space allowed in thematic breaks

### ISSUE THREAD

**Issue by ScottAbbey** [commonmark/commonmark-spec#464]
From CommonMark 0.27:

> A line consisting of 0-3 spaces of indentation, followed by a sequence of three or more matching -, _, or * characters, each followed optionally by any number of spaces, forms a thematic break.

The general structure of this rule has been in place in CommonMark for some time, however, it may require an update.

Since CommonMark 0.21, tabs are no longer expanded to spaces except where whitespace helps to define block structure.  Any amount of whitespace between thematic break markers will not affect block structure, so tabs should not be expanded to whitespace in the following example:
```
*→*→*
```

However, the commonmark.js dingus reports the following output for the preceding example:
```
<hr />
```

It appears that either the commonmark.js dingus is expanding tabs to spaces in this instance, or the rule must be updated to say that both spaces and tabs are allowed within thematic break lines.

Testing the pattern in [babelmark](https://johnmacfarlane.net/babelmark2/?text=*%09*%09*) shows most implementations treat this input as a thematic break, but there is some disagreement.

**Comment by mgeier** [comment]
See also #410.

**Comment by jgm** [comment]
We tried to make a minimal change in 0.21, so the beginning
of the Tabs section says

> Tabs in lines are not expanded to spaces. However, in contexts where whitespace helps to define block structure, tabs behave as if they were replaced by spaces with a tab stop of 4 characters.

The intent was that we would not have to change everything
that refers to spaces in the spec to mention tabs as well.
Since tabs behave as if they were replaced with spaces,
the spec for thematic breaks applies to the case with tabs
as well.

Perhaps this isn't ideal, but the changes required to
explicitly mention tabs everywhere they can occur are
somewhat extensive, and I haven't had time or energy
to make them.  If someone else wants to take this on in a
systematic way, it would probably be an improvement, but
this is not the only context affected.

**Comment by ScottAbbey** [comment]
Okay, I understand the rule better now and I see where I had previously misinterpreted it.

I was aware of the rule attached to the explanation of tabs, but I misunderstood the "context where whitespace helps to define block structure" and its interactions with the rule on thematic breaks.

My statement above:

> Any amount of whitespace between thematic break markers will not affect block structure

Was in error, because the insertion of some types of whitespace, for instance a "line tabulation (U+000B)", would indeed affect the block structure of what would otherwise be a thematic break.  My misunderstanding arose from previously assuming, like mgeier in the linked thread, that this was specifically targeting things like spaces for indentation.

Since this same misunderstanding has affected multiple people, perhaps it would be a good idea to further clarify this expansion rule in section 2.2.  Not changing the behavior, which seems to be sound, but just making it more explicit.

I haven't seen this treatment specifically worked out in the linked thread or elsewhere, so could you confirm that my interpretation here is the reason tabs are treated as spaces in e.g. thematic breaks and ATX headings?

***

Example of the following basic pattern for a thematic break:
```
[0]*[1]*[2]*[3]
```

If all of locations 0, 1, 2, and 3 are empty, the line forms a thematic break.

If four or more spaces are included at location 0, the block is no longer a thematic break, so tabs should be treated as spaces there.

Any number of spaces would be fine in locations 1, 2, and 3, but if location 1, 2, or 3 contained the whitespace character "line tabulation (U+000B)", the line would no longer be a thematic break, since those are not "spaces". Thus, tabs in these locations are treated as if they were spaces.

***

After inspecting other similar contexts like ATX headings, it appears that this is now treated consistently consistent throughout the spec and reference implementation.  If *any* whitespace character(s, or lack of) in that position could change the block structure, a tab in that location will be treated as if it were spaces.

Can you confirm that this is the correct reasoning for why this behavior follows from the rule? If so, I would recommend being a bit more explicit about what "contexts where whitespace helps to define block structure" means.  It is too subtle as-is.  Elaborating a bit more on the 2.2 rule will help make it more clear that all these references to "spaces" throughout the document also apply to expanded tabs.  I actually think it is possibly better to *not* specifically say "spaces or tabs" in each of these locations.

All this, of course, hinges on there not being any counterexample where this rule doesn't quite hold.
