### ISSUE TITLE
Unclear: Character References for Control Characters

### ISSUE THREAD

**Issue by fiveop** [commonmark/commonmark-spec#474]
I would have expected, that `&#10`; should be handled like an escaped line feed character. However, the implemention used by the dingus basically ignores it.

I cannot find text in the specification supporting either my assumption nor the exhibited behaviour.

**Comment by jgm** [comment]
It is treated exactly like an _unescaped_ line feed character, per the spec.

> All valid HTML entity references and numeric character references, except those occuring in code blocks and code spans, are recognized as such and treated as equivalent to the corresponding Unicode characters.

**Comment by fiveop** [comment]
Thank you and sorry.

**Comment by fiveop** [comment]
I reopen this issue, because I cannot reconcile Example 475 with HTML entity references being treated like unescaped characters:

```
[link](/url "title \"&quot;")
```

The entity reference occurs in the context of a link title and not plain text. But why are entity references lumped in with escaped characters in one case and with unescaped ones in the other?

**Comment by aidantwoods** [comment]
@jgm 
> It is treated exactly like an *unescaped* line feed character, per the spec.

Surely you mean an *escaped* or *literal* character. Otherwise, why isn't this a blockquote?

```markdown
&gt; hello
```

**Comment by mgeier** [comment]
I'm not sure, but this is probably related to my question [When exactly should numeric character references be replaced?](https://talk.commonmark.org/t/when-exactly-should-numeric-character-references-be-replaced/2121).

**Comment by jgm** [comment]
Perhaps we need to clarify this in the spec.

**Comment by mgeier** [comment]
@jgm I like your update to the spec, but I think there is still information missing, which I'm trying to add in #572.
