### ISSUE TITLE
Info string for multiple code blocks

### ISSUE THREAD

**Issue by cup** [commonmark/commonmark-spec#548]
Stack Exchange Markdown allows to specify language for multiple code blocks:

~~~
<!-- language-all: lang-php -->

    print "alpha beta\n";
~~~

https://stackoverflow.com/editing-help#syntax-highlighting

However CommonMark seems to have no way to do this, which mean you must use info
string for each block:

<pre>
~~~php
print "alpha beta\n";
~~~

~~~php
print "gamma delta\n";
~~~
</pre>

https://spec.commonmark.org/0.28#fenced-code-blocks

**Comment by cup** [comment]
https://github.com/github/cmark-gfm/issues/133

**Comment by Crissov** [comment]
Some engines support (arbitrary) document metadata specified in [YAML format](https://yaml.org), which could look like this:

~~~~ markdown 
---
default-code-language: PHP
---
~~~~

**Comment by jgm** [comment]
This is an implementation issue.  An implementation may want to offer a way to add a default info string to unmarked code blocks.  That shouldn't affect parsing, which is what the spec is about.  The default info string can be added by walking the AST after parsing.
