### ISSUE TITLE
Skipping heading ranks

### ISSUE THREAD

**Issue by cup** [commonmark/commonmark-spec#560]
With Asciidoc, it is recommended to keep headings in order. That is to say, H4
should not follow H2, better for H3 to follow H2. If you break this it gives a
warning:

~~~
asciidoctor: WARNING: readme.adoc: line 11: section title out of sequence:
expected level 2, got level 3
~~~

i was somewhat surprised by this, but then i noticed this is an official
recommendation as well:

- https://developer.mozilla.org/Web/HTML/Element/Heading_Elements#Usage_notes
- https://w3.org/WAI/tutorials/page-structure/headings

Markdown has no restriction on header order and in fact doesnt even advise
against out of order headings:

https://spec.commonmark.org/0.28#atx-headings

**Comment by cup** [comment]
https://github.com/commonmark/CommonMark/issues/560
https://github.com/jgarber/redcloth/issues/56
https://github.com/ruby/rdoc/issues/700
https://github.com/wallyqs/org-ruby/issues/65

**Comment by jgm** [comment]
These claims are all true, but I'm not sure what is being suggested here.

**Comment by cup** [comment]
@jgm thanks for comment - suggestion would be to put recommendation here:

https://spec.commonmark.org/0.28#atx-headings

and/or produce are warning with any resultant HTML that was formed from markdown with misordered headings
