### ISSUE TITLE
Feature Request: UML diagrams

### ISSUE THREAD

**Issue by davic80** [commonmark/commonmark-spec#573]
It will be very helpful to add the feature to render UML diagrams using [Mermaid](https://mermaidjs.github.io/)

**Comment by jgm** [comment]
This is probably not generic enough to be an extension, and anyway we're trying to keep discussion of extensions to talk.commonmark.org.

Usually one handles such things by putting the code in a specially marked code block, and applying a filter.  [lcmark](https://github.com/jgm/lcmark) is one implementation that has a framework for creating such filters. Or you can just use pandoc, which supports commonmark (`-f commonmark`) and has a system of filters.  In fact there's already one for [plantuml diagrams](https://github.com/pandoc/lua-filters/tree/master/plantuml).  Don't know about Mermaid, but it would probably be easy to modify this filter to use it.
