### ISSUE TITLE
Reference Link Definitions Should Not Be Allowed in Lists

### ISSUE THREAD

**Issue by neildaniels** [commonmark/commonmark-spec#576]
Currently, if there is something that _appears_ to be a reference-link definition within a bulleted list, it is interpreted as a definition instead of using the an actual definition.

```
- [Example]: Single
- This [Example]: works
- [Other]: Double Word

[Example]: https://www.example.com
[Other]: https://www.example.com/other
```

is parsed as

```html
<ul>
<li></li>
<li>This <a href="Single">Example</a>: works</li>
<li><a href="https://www.example.com/other">Other</a>: Double Word</li>
</ul>
```

but would expect it to be 

```html
<ul>
<li><a href="https://www.example.com">Example</a>: Single</li>
<li>This <a href="Single">Example</a>: works</li>
<li><a href="https://www.example.com/other">Other</a>: Double Word</li>
</ul>
```

**Comment by jgm** [comment]
Well, reference link definitions *are* allowed inside list items (and any block container).
And this
```
[Example]: single
```
*is* a valid reference link definition.  And the spec does say that earlier definitions get priority.  So, as far as I can see, this behavior is in accord with the spec.

**Comment by neildaniels** [comment]
Gotcha. Yes, by that definition I understand what's going on. This isn't something that all Markdown parsers do, so it was unexpected by me.
