### ISSUE TITLE
Natural way to disable autolink

### ISSUE THREAD

**Issue by GitClickOk** [commonmark/commonmark-spec#577]
What the natural way to disable an autolink? By example:

`I will develop my website using ASP.NET Core.`

Autolink feature will turn "ASP.NET" in a link, but I don't want this behavior. There are only hacks/tricks to fix this, you can see [here](https://stackoverflow.com/q/25706012/48729). The best one is enclosing in backticks, but this will change the formatting.

I understand a MD file must be legible reading sources and reading via preview, so a solution like this is terrible:

`I will develop my website using ASP<i></i>.NET Core.`

I cannot think a nice solution right now, but I think it is really a problem that needs to be thought about.

**Comment by vassudanagunta** [comment]
CommonMark [autolinks](https://spec.commonmark.org/0.29/#autolinks) are explicit. CommonMark cannot be the source of your issue. 

You may be using an editor that automatically converts text that looks like a link, such as `commonmark.org`, to a CommonMark autolink `<commonmark.org>`. Your problem then is not CommonMark, but the editor. 

It is worth noting that in other cases where you want to "disable" CommonMark syntax, you use [backslash escapes](https://spec.commonmark.org/0.29/#backslash-escapes). This is made explicit in [this example](https://spec.commonmark.org/0.29/#example-300) in the spec. A backslash escape may even disable your editor's automatic behavior.

**Comment by GitClickOk** [comment]
@vassudanagunta Thank you, the editor/preview I'm using are from VSCode and Markdown Preview Enhanced Extension. Looks backslashes cannot avoid this behavior, I will check if VSCode and this extension have some option to disable this.

**Comment by Crissov** [comment]
Backslash escapes for the dot as in `ASP\.NET` _should_ work in an implementation build upon Commonmark. @vassudanagunta is right otherwise.
