### ISSUE TITLE
how to escape backtick between backticks? .e.g `a`b`

### ISSUE THREAD

**Issue by localhostdotdev** [commonmark/commonmark-spec#579]
some attempts:

```markdown
`a`b` # => <code>a</code>b`
`a\`b` # => <code>a\</code>b`
`a\\`b` # => <code>a\\</code>b`
`a``b` # => <code>a``b</code>
`a`\``b` # => <code>a</code>`<code>b</code> (closest)
```

so I'm using the last option for now but would rather have one `<code>` as the rendering is different

tested with common mark: https://spec.commonmark.org/dingus/?text=%60a%60b%60%0A%0A%60a%5C%60b%60%0A%0A%60a%5C%5C%60b%60%0A%0A%60a%60%60b%60%0A%0A%60a%60%5C%60%60b%60%0A

**Comment by Crissov** [comment]
~~~~ markdown
``a`b``
~~~~

**Comment by localhostdotdev** [comment]
of thanks sorry
