### ISSUE TITLE
javascript execute(xss) in  all version

### ISSUE THREAD

**Issue by 0FuzzingQ** [commonmark/commonmark-spec#585]
## desc

A new js paylod can be executed in commonmark so that leads to xss vuln

this is the payload:

`[click me!](javascript:window.onerror=alert;throw%20 "xss")`

it may be caused by uncompletely security filter against xss payload like 

`javascript:window.onerror`

## show

![image](https://user-images.githubusercontent.com/27672638/57834654-5e084480-77ef-11e9-8dc7-0f5f088421b7.png)

we can see that our markdown payload has benn successfully convert to executable js code 

![image](https://user-images.githubusercontent.com/27672638/57834768-97d94b00-77ef-11e9-9cf2-0b565ccc9e97.png)

## solution

filter it

**Comment by jgm** [comment]
Do you know that the commonmark.js library can be used with the `safe` option, which will cause this to be filtered?

The dingus does not enable this option, since it seems fairly harmless to allow users to xss themselves.
