### ISSUE TITLE
Spec 0.29 example 2 ambiguity

### ISSUE THREAD

**Issue by gkjpettet** [commonmark/commonmark-spec#588]
I think there is some ambiguity in example 2:

```
••→foo→baz→→bim
```

The spec says this should output:

```html
<pre><code>foo→baz→→bim
</code></pre>
```

The spec states:

> in contexts where whitespace helps to define block structure, tabs behave as if they were replaced by spaces with a tab stop of 4 characters.

And slightly later in the same section it states:

> In the following case  `>`  is followed by a tab, which is treated as if it were expanded into three spaces. Since one of these spaces is considered part of the delimiter,  `foo`  is considered to be indented six spaces inside the block quote context, so we get an indented code block starting with two spaces

Doesn't this mean that the output of example 2 should be:

```html
<pre><code>••foo→baz→→bim
</code></pre>
```

I.e: why is the tab before foo not being expanded at all? This seems confusing.

**Comment by Crissov** [comment]
The _tab stop interval_ is fixed to 4 columns (or spaces or characters), therefore the integer _tabulator width_ ranges from 1 through 4 columns, while otherwise the _character width_ (of spaces, `#`, `>`, `*`, `-`, `+`, `0`–`9`, `.`, `)` in particular) is fixed to 1 column.

**Comment by jgm** [comment]
That's right: the way tab stops work, SPACE + SPACE + TAB expands to four spaces, when the tab stop is 4 spaces.  TAB just moves you to the next multiple of 4 in the line position; how many spaces that requires depends on where you are in the line.
