### ISSUE TITLE
em dash and en dash

### ISSUE THREAD

**Issue by cup** [commonmark/commonmark-spec#593]
When used inline, this markup:

~~~
aa --- bb
~~~

should produce em dash U+2014, and this markup:

~~~
aa -- bb
~~~

should produce en dash U+2013. It seems these are defined in the reference
implementation:

https://github.com/commonmark/cmark/blob/master/test/smart_punct.txt

but not in the spec. More links:

- https://daringfireball.net/projects/smartypants
- https://wikipedia.org/wiki/Dash

**Comment by cup** [comment]
https://github.com/commonmark/commonmark-spec/issues/593
https://github.com/github/markup/issues/1032
https://github.com/github/markup/issues/1281

**Comment by jgm** [comment]
This is an optional extension, not part of the official spec.

**Comment by cup** [comment]
@jgm it should still be documented...

this is how its done with POSIX:

> Extension to the ISO C standard
The functionality described is an extension to the ISO C standard. Application developers may make use of an extension as it is supported on all POSIX.1-2017-conforming systems.

https://pubs.opengroup.org/onlinepubs/9699919799/functions/time.html

and Python:

> Note that on some platforms, trying to open a filename using this function, may work and start the operating system’s associated program. However, this is neither supported nor portable.

https://docs.python.org/library/webbrowser

**Comment by jgm** [comment]
Extensions are unofficial at this point.  It is documented in the text file you linked to, which is part of the processor that supports the extension.  But it's not yet part of the spec.

**Comment by cup** [comment]
https://i.imgur.com/vXDWqIH.jpg
