### ISSUE TITLE
Clarify escapes in link reference definitions

### ISSUE THREAD

**Issue by wooorm** [commonmark/commonmark-spec#600]
[Link reference definitions](https://spec.commonmark.org/0.29/#link-reference-definitions) consist (sometimes optionally) of link labels, unbracketed link destinations, and single, double, or bracketed (parens) link titles.

These segments can include escaped characters (specifically `]`, `(`, `)`, `'`, and `"`).
However, for the definition of these segments, link reference definitions reference links, which are inline.
The problem here is that *inline* constructs have a concept of escapes, whereas *block* constructs don’t.
Link reference definitions are the only *block* construct that mention escapes.

The problem here is that it’s a bit ambiguous what “escape” is in block constructs? As there are apparently escapes in blocks, are they backslash escapes? Are “hard line breaks” includes in definitions? Is `x\\]` fine, because it is a backslash and a right square bracket? 🤷‍♂️

N.B. I think I get what the spec is going for, to parse backslash escapes (as in, ascii punctuation) but not hard line breaks, however, I think it may be good to clarify the spec text.

**Comment by Crissov** [comment]
Just an aside: the link destination may be “bracketed”, of course, i. e. include a `<` prefix and a `>` suffix.

**Comment by wooorm** [comment]
@Crissov Definitely, but I didn’t mention it because parsing of bracketed (as in, angle brackets) around a link destination doesn‘t include escapes, according to the spec as it currently is.

**Comment by jgm** [comment]
Maybe the subsection on "backslash escapes" should simply be moved out of the Inlines section, and into Preliminaries.  It makes many references to both block and inline contexts, so it's not meant to apply only to inlines.  (I can see how you'd be led to think that, though.)  The section on backslash escapes tries to list all of the contexts where backslash escapes don't work. If there are omissions, please let us know.

**Comment by wooorm** [comment]
> It makes many references to both block and inline contexts

Yeah that can work! I think the contextual problem arises from the block syntax linking to the inline syntax for its definitions, which includes backslash escapes. This would solve that.

Come to think of it, a related issue may be that character references can also be used to “escape” syntax, in this particular case `&#93;`, or its hexadecimal version, for `]`. Can they be used in the link reference definition label, destination, title? Would they need to be moved up as well?
It may also be good to group them both “escapes”, and in the rest of the document use the term “escape” instead of specifically “backslash-escaped” ([such as here](https://spec.commonmark.org/0.29/#link-label))
