### ISSUE TITLE
ASCII control characters

### ISSUE THREAD

**Issue by wooorm** [commonmark/commonmark-spec#602]
There are two mentions of ASCII control characters in the spec text:

* [Link destination](https://spec.commonmark.org/0.29/#link-destination)
* [Absolute URI](https://spec.commonmark.org/0.29/#absolute-uri)

But what a control character is, is not defined.

I suggest defining them e.g. below [non whitespace character](https://spec.commonmark.org/0.29/#non-whitespace-character), along these lines:

> An [ASCII control character](@) is any character between U+0000–1F (both including) or U+007F.

...and linking to it from the two spec texts.

I can create a PR if this addition is good.

**Comment by jgm** [comment]
Yes, good idea. a PR would be welcome.
