### ISSUE TITLE
Conflict between tab (ex 10) and ATX heading

### ISSUE THREAD

**Issue by jo-so** [commonmark/commonmark-spec#612]
The definition of [ATX heading](https://spec.commonmark.org/0.29/#atx-headings) says:
> The opening sequence of # characters must be followed by a **space** or by the end of line.

The definition given for [space](https://spec.commonmark.org/0.29/#space) is:
> A space is U+0020.

But [example 10](https://spec.commonmark.org/0.29/#example-10) says `#→Foo` should become `<h1>Foo</h1>`.

The current implementation of dingus allows a [tab before and after the ending closing sequence](https://spec.commonmark.org/dingus/?text=%23%09Foo%20%09%20##%20%09%20%0A):
```
#→Foo → ## → 
```

The spec should allow tabs the same like spaces.

**Comment by jo-so** [comment]
Similarly, dingus [strips trailing tabs after setext headings marker](https://spec.commonmark.org/dingus/?text=Foo%0A%09----%09%09%0A), while the spec states »any number of trailing *spaces*«.

**Comment by jgm** [comment]
See the general remark about spaces and tabs in the spec: beginning of sec. 2.2, "in contexts where whitespace helps to define block structure, tabs behave as if they were replaced by spaces with a tab stop of 4 characters.".

This is too implicit and trips up a lot of people, so it can be improved, but we already have an issue for this: see #386

**Comment by jgm** [comment]
For background https://talk.commonmark.org/t/proposed-change-in-tab-handling/1219
