### ISSUE TITLE
Raw HTML declaration casing inconsistency between spec and reference parser

### ISSUE THREAD

**Issue by wooorm** [commonmark/commonmark-spec#620]
For block HTML, a declaration is as follows:

> **Start condition**: line begins with the string `<!` followed by an uppercase ASCII letter.
> **End condition**: line contains the character `.

For raw HTML (inline), it is as follows:

> A declaration consists of the string `<!`, a name consisting of one or more uppercase ASCII letters, whitespace, a string of characters not including the character `>`, and the character `>`.

---

The reference parser does not seem to care about the inline HTML restriction on uppercase ASCII letters:

```
asd <!doctype html>

<!doctype html>
```

**CM**:

```
<p>asd <!doctype html></p>
<p><!doctype html></p>
```

Note that both are inline, and both “work”.

---

I am raising this issue here as I think a better solution is to change the spec, to allow ASCII lowercase alphas in declarations, as HTML also allows them.

**Comment by jgm** [comment]
If HTML allows them (can you link to the spec?) then certainly we should too.

**Comment by jgm** [comment]
OK, let's change this.  Do you want to do a PR?

**Comment by wooorm** [comment]
Done!
