### ISSUE TITLE
Newlines inside lists break them

### ISSUE THREAD

**Issue by fabiospampinato** [commonmark/commonmark-spec#628]
Just above example 276, in the section regarding lists, the spec mentions:

> There can be any number of blank lines between items:

Which doesn't seem to be quite true, in the sense that adding newlines between items will cause items to be rendered as paragraph, messing up the rendering. 

Technically what gets rendered is still a single list, but:

1. [This](https://spec.commonmark.org/dingus/?text=-%20foo%0A-%20bar%0A-%20baz%0A) is what a proper single list of 3 items looks like.
2. [This](https://spec.commonmark.org/dingus/?text=-%20foo%0A%3C!--%20--%3E%0A-%20bar%0A%3C!--%20--%3E%0A-%20baz%0A) is what 3 separate lists, separated by HTML comments (I wonder how many people know about this), look like.
3. [This](https://spec.commonmark.org/dingus/?text=-%20foo%0A%0A-%20bar%0A%0A-%20baz%0A) is what a single list containing 3 items separated by newlines looks like, as you can see as far as the eye can tell it looks identical to point number 2, i.e. 3 separate lists.

Are there any reasons for why case number 3 should not look like case number 1 (i.e. no `p` tags getting rendered)?

**Comment by jgm** [comment]
Yes, there is a reason.  See the spec's discussion of tight vs. loose lists:
<https://spec.commonmark.org/0.29/#loose>

This behavior goes all the way back to the original Markdown syntax description.

**Comment by fabiospampinato** [comment]
> (The difference in HTML output is that paragraphs in a loose list are wrapped in <p> tags, while paragraphs in a tight list are not.)

I can understand that CommonMark is aligning with the original `Markdown.pl` thing here for maximum backwards compatibility, but it'd bet it's way more common to insert a newline by mistake and have your lists messed up by that than inserting a newline on purpose in order to have list items wrapped in paragraphs 🤨. It'd be interesting to know the original reasoning behind this behavior.
