### ISSUE TITLE
Example 118 emphasizing needs whitespace to be rendered

### ISSUE THREAD

**Issue by stp-ip** [commonmark/commonmark-spec#633]
Within the demo renderer linked from example 118 the emphasized word isn't rendered as mentioned within the example.
Example given:
```**Hello**```  -> rendered as ```**Hello**```

Expected result:
```**Hello**``` -> rendered as **Hello**

Prefixing this with whitespace fixes it.

Not sure, if this is intentional not to render without a preceding whitespace and therefore just an issue within the demo and example or if the implementation of the renderer is not rendering correctly.

Sidenote: This seems to also be the case with github.com/yuin/goldmark

Example 118: https://spec.commonmark.org/0.29/#example-118

Demo 118: https://spec.commonmark.org/dingus/?text=%3Ctable%3E%3Ctr%3E%3Ctd%3E%0A%3Cpre%3E%0A**Hello**%2C%0A%0A_world_.%0A%3C%2Fpre%3E%0A%3C%2Ftd%3E%3C%2Ftr%3E%3C%2Ftable%3E%0A

**Comment by jgm** [comment]
I don't understand.  In the spec, it says the `**Hello**` should be rendered as `**Hello**`.
And that is exactly what I'm seeing in the dingus.  What is the problem?  (See the explanation in the spec as to why it is not rendered as bold here.)

**Comment by stp-ip** [comment]
Damn missed that note. So this is intentional behavior in all implementations to not render markdown, if it isn't preceded by newline or whitespace.
Was coming from another implementation and in the context it was showing up it felt weird.

Sorry for misunderstanding. Thanks for taking the time.

Nothing to see here. Move along :P
