### ISSUE TITLE
Quoting a markdown code sample

### ISSUE THREAD

**Issue by stdedos** [commonmark/commonmark-spec#635]
What would be the expected output of this?

> ```
> 	```console
> 	yu@hu:~$ sudo apt install php libapache2-mod-php
> 	yu@hu:~$ sudo systemctl restart apache2
> 	yu@hu:~$ systemctl status php7.2-fpm
> 	* php7.2-fpm.service - The PHP 7.2 FastCGI Process Manager
> 	   Loaded: loaded (/lib/systemd/system/php7.2-fpm.service; enabled; vendor preset: enabled)
> 	   Active: active (running) since Sat 2018-06-30 23:56:14 PDT; 1min 28s ago
> 	     Docs: man:php-fpm7.2(8)
> 	 Main PID: 10080 (php-fpm7.2)
> 	   Status: "Processes active: 0, idle: 2, Requests: 0, slow: 0, Traffic: 0req/sec"
> 	    Tasks: 3 (limit: 2321)
> 	   CGroup: /system.slice/php7.2-fpm.service
> 	           |-10080 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
> 	yu@hu:~$ sudo systemctl restart nginx
> 	yu@hu:~$ sudo apt install php-[extname]
> 	```
> ```

Both Github, (and https://spec.commonmark.org/dingus/) produce the same weird-looking 
![image](https://user-images.githubusercontent.com/133706/74182041-f92d2e00-4c4a-11ea-9b3c-55e3eb3ba615.png)
this.

"Fixing" it (or somewhat ignoring it) could be easy
![image](https://user-images.githubusercontent.com/133706/74182129-24b01880-4c4b-11ea-9e48-b3e664555b3e.png)

but it is still missing the expected closing ` ``` `

**Comment by jgm** [comment]
This is because according to the spec,

> The closing code fence may be indented up to three spaces.

So what's happening here is that the indented closing ` ``` ` is closing the outdented one.

A possible modification would say that the closing backtick span cannot be indented more than the opening one.

However, this isn't a big issue in practice. If you want to quote a backtick span in markdown, just use a *longer* backtick span at the outer level.  The closing span must have at least as many backticks as the opening span.

**Comment by stdedos** [comment]
> This is because according to the spec,
> 
> > The closing code fence may be indented up to three spaces.

On that indentation, I have used tabs. What is the "tab-to-space" conversion rate?
Or, by "spaces" the spec means "vertical-space characters"?

> However, this isn't a big issue in practice. If you want to quote a backtick span in markdown, just use a _longer_ backtick span at the outer level. The closing span must have at least as many backticks as the opening span.

Wooow. I didn't know that 😄 

With the lack of non-3-backticks examples (except this https://github.com/commonmark/commonmark-spec#the-spec, but I thought that this was "a mistake" and "your parsing"), and after "knowing" that `Markdown.pl` has "undefined" behaviors, I thought it was just a coincidence that longer starting backticks (and unbalanced backticks) was working in places (because e.g. Github does not use Commonmark).

i.e., in regex, I'd think that the opening and the closing matchers were something like ` \s+```+(\w+)?$ `,  ` \s+```+$ ` respectively

**Comment by jgm** [comment]
It was *really* difficult to talk about markdown on GitHub before they switched to commonmark, because of just this issue.  The ability to use longer fences is key.

**Comment by jgm** [comment]
Btw GitHub does use commonmark, at least for issue comments.
They use a slightly extended version of the commonmark reference parser, cmark.

**Comment by stdedos** [comment]
> Btw GitHub does use commonmark, at least for issue comments.
> They use a slightly extended version of the commonmark reference parser, cmark.

🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯🤯

Thank you for all the knowledge provided! Since when are they using commonmark? They still advertize "Markdown" and "Github Flavored Markdown", not Commonmark

**Comment by jgm** [comment]
https://github.blog/2017-03-14-a-formal-spec-for-github-markdown/

**Comment by stdedos** [comment]
Thank you for your information. I would otherwise close this ticket; feel free to handle as you wish.

**Comment by wooorm** [comment]
@jgm I think this can be closed?

**Comment by stdedos** [comment]
Apologies, I got carried away from the good discussion and I forgot to take care of it
