### ISSUE TITLE
Extend markdown files by including other files

### ISSUE THREAD

**Issue by rustysys-dev** [commonmark/commonmark-spec#647]
I do not know if this is the place to request/discuss this.  But It would be wonderful to see the markdown specification extended to include the ability to import content.

    # my header
    
    include::content.md
    
    # my second header 
    
    code block
    
    ```python
    include::code.py
    ```

If this is not the place to propose this feature, where should I ask?

**Comment by vassudanagunta** [comment]
The proper place is talk.commonmark.org. In fact it [has already been suggested](https://talk.commonmark.org/t/transclusion-or-including-sub-documents-for-reuse/270?u=vas).
