### ISSUE TITLE
Textarea should be treated as a multiline HTML block

### ISSUE THREAD

**Issue by ColdHeat** [commonmark/commonmark-spec#657]
The Commonmark spec says for HTML blocks (rule 1), that `<script` , `<pre` , or `<style` tags should start an HTML block and not be terminated until the end tag is found.

Although not specifically markup, `<textarea>` should be included in this rule because it is a multi-line element. If you include a multi-line textarea the rendering will break the contents in the textarea.

![image](https://user-images.githubusercontent.com/166333/87257757-ab238d00-c46b-11ea-8f6e-6acf28936076.png)

Discussion post on this issue: https://talk.commonmark.org/t/textarea-as-multi-line-html-block/3550

**Comment by ColdHeat** [comment]
@jgm what's the process for renderers (i.e. cmark) to adopt this change?

**Comment by jgm** [comment]
I already made the change in cmark and commonmark.js.

**Comment by ColdHeat** [comment]
Thank you for being amazing!
