### ISSUE TITLE
compatibility issue with h1/h2 syntax and hr and lists

### ISSUE THREAD

**Issue by wolftune** [commonmark/commonmark-spec#664]
```
hello
---
```

correctly uses the `---` to indicate an h2

```
1. hello
---
```

breaks the `---` which now renders as an hr and the `1. hello` renders as ol

The spec isn't clear on this, but because inserting the hr breaks the list, it seems to me that it should work as h2 still. Because sometimes someone wants a manually inserted `1.` within a header title. If they want an hr after the end of a list, that could require an extra line break perhaps…

**Comment by jgm** [comment]
The spec *is* clear on this:
"The lines of text must be such that, were they not followed by the setext heading underline, they would be interpreted as a paragraph: they cannot be interpretable as a code fence, ATX heading, block quote, thematic break, list item, or HTML block."
