### ISSUE TITLE
Confusing definition of HTML flow type 7

### ISSUE THREAD

**Issue by wooorm** [commonmark/commonmark-spec#665]
The HTML flow type 7 (complete tag) seems to indicate with its start condition:

> 7. **Start condition**: line begins with a complete open tag (with any tag name other than script, style, or pre) or a complete closing tag, followed only by whitespace or the end of the line.

...that the following matches:

```markdown
<x> a
```

Because it is a full opening tag, followed by a space (which is whitespace)

[cmjs](https://github.com/commonmark/commonmark.js/blob/21fb17085f7711a726559232329bacd03da7c621/lib/blocks.js#L24) doesn’t see it as such:

```html
<p><x> a</p>
```

It seems that the start condition should be worded as:

> 7. **Start condition**: line begins with a complete open tag (with any tag name other than script, style, or pre) or a complete closing tag, followed by **zero or more spaces and tabs, followed by the end of the line.**

Or is this a bug in implementations?

I can open a PR with an agreeable fix to the spec.

**Comment by jgm** [comment]
I figured that "followed only by whitespace" implies "not followed by whitespace AND a letter."
But I agree, this could be more explicit, so I'd be happy with a PR.
