### ISSUE TITLE
Wrong html generation while using html-blocks

### ISSUE THREAD

**Issue by mueller-jens** [commonmark/commonmark-spec#668]
In the [example 118](https://spec.commonmark.org/0.29/#example-118) the generated html is not valid. In my eyes the `</p>` tag should be before the `</pre>` tag.

The result we get:

```
<table><tr><td>
<pre>
**Hello**,
<p><em>world</em>.
</pre></p>
</td></tr></table>
```

The expected result:

```
<table><tr><td>
<pre>
**Hello**,
<p><em>world</em>.
</p></pre>
</td></tr></table>
```

**Comment by jgm** [comment]
The example is just illustrating how the rules work. The rules are not guaranteed to produce valid HTML.  (If you include raw HTML in your document, you're responsible for making it correct and knowing how the parser will interpret it.)
