### ISSUE TITLE
Parsing of underscores in URLs

### ISSUE THREAD

**Issue by habi** [commonmark/commonmark-spec#670]
[Today I learned](https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$Uigd8z2GrqWalQBdNkvylgUoFpUTjhrymFF4rx-w7bo?via=matrix.org&via=privacytools.io&via=tchncs.de) that [Element.io](https://element.io) uses Commonmark.

And I was shared a link to a room, namely https://app.element.io/#/room/#_oftc_#osm-ch:matrix.org

Commonmark parses this as <img width="375" alt="Screenshot 2020-11-26 at 22 48 04" src="https://user-images.githubusercontent.com/1651235/100393291-750d3100-3039-11eb-9bc9-64d5c76db65e.png"> and breaks the URL into two pieces.
These two pieces *can* be copy-pasted to a browser, but then don't link to the correct place anymore.

I think that underscores in URLs should *not* be parsed, like [GFM](https://github.github.com/gfm/) does not and keep the URL intact.

**Comment by wooorm** [comment]
CommonMark doesn't support just a url. GFM does. So, this sounds more like a problem with GFM? It's not a lot of info to go on to debug your problem...

**Comment by habi** [comment]
When I paste the link on https://spec.commonmark.org/dingus/ 'oftc' is rendered italic. It's also italic when I'm sent the link in Element and breaks the URL into two pieces. I *can* copy the link from the rendered view, but the it is wrong because the two underscores are not in the pasted URL anymore.

**Comment by habi** [comment]
> So, this sounds more like a problem with GFM?

No, GFM keeps the link intact by not rendering oftc italic.

**Comment by Crissov** [comment]
CommonMark does not support "autolinks" directly, but GFM and other implementations include an extension that parses raw URLs into links. In vanilla CM you world have to enclose an URL with angular brackets to have it recognized. No markup inside of the address will be applied then:

    <https://app.element.io/#/room/#_oftc_#osm-ch:matrix.org>
    <https://app.element.io/#/room/%23_oftc_%23osm-ch:matrix.org>

**Comment by jgm** [comment]
Or, if you don't want it to be a hyperlink, use code backticks
```
`https://app.element.io/#/room/#_oftc_#osm-ch:matrix.org`
```

**Comment by habi** [comment]
I know that I can use either backticks or angular brackets, but the user that sends me the link might not, breaking the link for me.

Does that mean that Element.io implements the ComomMark specs wrongly, because the URL that is sent to me is autolinked (and broken up in the process)?

**Comment by Crissov** [comment]
It means that Element.io implements a superset of CommonMark and the problem lies weiterhin their extension (which happens to be a common one).
