### ISSUE TITLE
Headings are listed as incorrect block type

### ISSUE THREAD

**Issue by seii** [commonmark/commonmark-spec#671]
According to the [0.29 spec](https://spec.commonmark.org/0.29/#container-blocks-and-leaf-blocks), a container block is simply a block "...which can contain other blocks." Both `ATX headings` and `Setext headings` are currently listed as "leaf blocks". However, both of those heading types can contain fenced code blocks, HTML blocks, and others. By definition, shouldn't this mean that both heading types are actually container blocks instead of leaf blocks?

Dingus examples:
[ATX heading with fenced code block](https://spec.commonmark.org/dingus/?text=%23%23%20%60%60%60test%60%60%60%0A)
[Setext heading with HTML block](https://spec.commonmark.org/dingus/?text=test%20%3Cstrong%3Etext%3C%2Fstrong%3E%0A---%0Acontinued)

**Comment by wooorm** [comment]
ATX contains a code span (e.g., one tick is the same as three), Setext heading contains a html span. Those aren’t blocks but have “inline” versions too.

**Comment by seii** [comment]
Ah, ok. It looks like I mistook the inline formatting for similar block types, then. Thank you for the clarification!
