### ISSUE TITLE
Table allignment

### ISSUE THREAD

**Issue by himanshu007-creator** [commonmark/commonmark-spec#674]
I would like top propose an issue. If we create a table in markdown  like the one below
| foo | bar |
| --- | --- |
| baz | bim |

we can align the data in cells to left, right or center. But we can't align the whole table to these directions. Tables created in markdown are  aligned to left by default. This needed to be worked upon. I am willing to work on this issue under guidance by a mentor. 
thanks

**Comment by jgm** [comment]
This spec currently does not include a table extension, so this is not the right place for this issue.
Please consider contributing to the thread on tables at talk.commonmark.org.
