### ISSUE TITLE
Reference implementation incorrectly detects setext heading as paragraph continuation text

### ISSUE THREAD

**Issue by jmholla** [commonmark/commonmark-spec#675]
Hi,

I've noticed this is also an issue in the [python commonmark library](https://github.com/readthedocs/commonmark.py)) and presumably [commonmark.js](https://github.com/jgm/commonmark.js). The spec says:

> Paragraph continuation text is text that will be parsed as part of the content of a paragraph, but does not occur at the beginning of the paragraph.

But, in the following, I would not expect TITLE to be paragraph continuation text but is rendered as part of the block quote:

```
> code
TITLE
=====
```

https://spec.commonmark.org/dingus/?text=%3E%20code%0ATITLE%0A%3D%3D%3D%3D%3D (You'll have to copy and paste this by hand or refresh the page once it's loaded.)

**Comment by vassudanagunta** [comment]
Block quotes are containers. They contain other elements such as paragraphs. In this case the block quote contains a single paragraph whose first line is `code\n` (the remainder of the line following the block quote marker). Then because of the paragraph continuation rules, `TITLE\n` is appended to that paragraph, and likewise `=====\n`

That's the whole point of paragraph continuation: to support laziness, the ability to continue paragraphs nested in containers *without* having to repeat the container demarcation (`>`, indentation) on every line.

Examples are all over the spec. Please take a look.

**Comment by jgm** [comment]
See sec 4.3

> The lines of text must be such that, were they not followed by the setext heading underline, they would be interpreted as a paragraph: they cannot be interpretable as a code fence, ATX heading, block quote, thematic break, list item, or HTML block.

and

> In general, a setext heading need not be preceded or followed by a blank line. However, it cannot interrupt a paragraph, so when a setext heading comes after a paragraph, a blank line is needed between them.

**Comment by jmholla** [comment]
In that case, the issue here is with the spec itself. From the definition of a block quote:

> [Laziness. If a string of lines Ls constitute a block quote with contents Bs, then the result of deleting the initial block quote marker from one or more lines in which the next non-whitespace character after the block quote marker is paragraph continuation text is a block quote with Bs as its content. Paragraph continuation text is text that will be parsed as part of the content of a paragraph, but does not occur at the beginning of the paragraph.](https://spec.commonmark.org/0.29/#block-quotes)

Take the following two sets of line

```
["> Title", "> ====="]
["> Title", " ====="]
```

If `" ====="` is paragraph continuation text, then those two must be the same because the result of removing the block quote marker from one or more lines of paragraph continuation text in a block quote should result in the same content. Since that is not the case, it cannot be paragraph continuation text and so it is not a part of the block quote.

There is an example that does show that this would be a part of the previous text, but I think the definition of paragraph continuation text does not accurately explain why that is the case.

**Comment by jgm** [comment]
Your original case had another line with `code`, and I was responding to that.

With this new case (with just two lines), there is indeed an issue, already noted in #460 (see also #634).
