### ISSUE TITLE
Unexpected behavior for hard wraps combined with headings

### ISSUE THREAD

**Issue by DanielRuf** [commonmark/commonmark-spec#677]
So far `\` seems to be the only solution to add manual breaks.

This works fine as long as normal text follows. But when you change the next line to a heading, the `\` is not evaluated anymore and is shown as is.

To me this makes not much sense.
Is this a flaw / bug in the specification?
In my opinion adding some manual linebreaks before a heading is a valid usecase.

<img width="925" alt="Bildschirmfoto 2021-03-30 um 19 35 48" src="https://user-images.githubusercontent.com/827205/113032803-8eadb900-9190-11eb-9014-fb46c08249a8.png">

**Comment by wooorm** [comment]
`\` doesn’t work at the end of something:

```
# heading\

> blockquote\

paragraph\
```

# heading\

> blockquote\

paragraph\

---

Your first example “prolongs” that paragraph: it’s *one* thing, two words with breaks in between.

If you want monospace, what about using indented/fenced code?

**Comment by wooorm** [comment]
And it is intentional, if that’s your question: https://spec.commonmark.org/0.29/#example-641.

For HTML, the way you seem to intent to use these breaks, is discouraged:
>  br elements must be used only for line breaks that are actually part of the content, as in poems or addresses.
> — https://html.spec.whatwg.org/#the-br-element

**Comment by jmooring** [comment]
The [specification](https://spec.commonmark.org/0.29/#hard-line-breaks) is pretty clear:

> A line break (not in a code span or HTML tag) that is preceded by two or more spaces **and does not occur at the end of a block** is parsed as a hard line break (rendered in HTML as a <br /> tag):

> For a more visible alternative, a backslash before the line ending may be used instead of two spaces:

> Hard line breaks are for separating inline content within a block. Neither syntax for hard line breaks works at the end of a paragraph or other block element:

**Comment by DanielRuf** [comment]
Hi @jgm,

can you clarify why this was closed?

**Comment by jgm** [comment]
I think you're trying to use hard breaks to do something that should be handled in another way.  (For example, if you want paragraphs to have more space between them, that's a presentational issue you can handle with CSS; similarly if you want more space before a heading.)  Commonmark is about representing structural elements of documents, not tweaking formatting.  (See also the quote above from the HTML spec about br.)

If you want, we can reopen the issue, but I'm not persuaded that the spec should change.

**Comment by DanielRuf** [comment]
Thanks for the clarification. I'm fine with this, I've already applied a workaround with a bit custom HTML.
