### ISSUE TITLE
Dingus doesn't handle the tabs according to the spec

### ISSUE THREAD

**Issue by farcaller** [commonmark/commonmark-spec#678]
Based on
>4.2 ATX headings

>An ATX heading consists of a string of characters, parsed as inline content, between an opening sequence of 1–6 unescaped # characters and an optional closing sequence of any number of unescaped # characters. **The opening sequence of # characters must be followed by a space** or by the end of line.
> ...

And the link to the space pointing at
> A space is U+0020.

I expect that `#\ttest` is not a heading. Dingus, however, interprets it as one:

```
<document xmlns="http://commonmark.org/xml/1.0">
  <heading level="1">
    <text>test</text>
  </heading>
</document>
```

**Comment by vassudanagunta** [comment]
[2.2 Tabs](https://spec.commonmark.org/0.29/#tabs):

> Tabs in lines are not expanded to spaces. However, in contexts where whitespace helps to define block structure, tabs behave as if they were replaced by spaces with a tab stop of 4 characters.

Further down in that section:

> [Example 10](https://spec.commonmark.org/0.29/#example-10)
> ```
> #→Foo
> ```
> ---
> ```
> <h1>Foo</h1>
> ```
