### ISSUE TITLE
Admonitions and Call Outs

### ISSUE THREAD

**Issue by mmerline** [commonmark/commonmark-spec#679]
Is there any flexibility in the CommonMark spec to expand basic markdown and add admonitions or “call outs?” These would make the spec more robust for notetaking and wiki use.

Here are how a few other notetaking apps and wiki systems define this feature:

> [Sublime Text [PlainNotes Package](https://packagecontrol.io/packages/PlainNotes)]
> When writing a note, you might need to distinguish a block or section by giving it a special title and box. These sections might appear several times in your document. Some examples would be Note, Tip or Caution blocks in an article.

> [[Markdeep](https://casual-effects.com/markdeep/)]
> Maruku + github + Admonition + CommonMark Markdown features: Admonitions (callout notes)

> [[MkDocs](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)]
> Admonitions, also known as call-outs, are an excellent choice for including side content without significantly interrupting the document flow. Material for MkDocs provides several different types of admonitions and allows for the inclusion and nesting of arbitrary content.
> Admonitions follow a simple syntax: a block must start with !!!, followed by a single keyword which is used as the type qualifier of the block and an optional title in quotes. The content of the block then follows on the next line, indented by four spaces. For example:
> ```
> !!! note
>    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
>    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
>    massa, nec semper lorem quam in massa.
> ```
> ```
> !!! note "Phasellus posuere in sem ut cursus"
>    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
>    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
>    massa, nec semper lorem quam in massa.
> ```

>[PyMdown Extensions]
>PyMdown Extensions is a collection of extensions for Python Markdown. They were originally written to make writing documentation more enjoyable. They cover a wide range of solutions, and while not every extension is needed by all people, there is usually at least one useful extension for everybody.

> [Paligo]
> Admonitions (sometimes called “safety messages” or “hazard statements” is an umbrella term used for the note, important, notice, caution, warning, danger and tip elements. You can add notes, warnings, tips, and other “admonition” elements to make parts of your content stand out. (Admonitions is the term for collectively describing all of the notes, warnings, tips, etc.).

Thanks for the consideration.

**Comment by jgm** [comment]
talk.commonmark.org is the place to discuss extensions.
