### ISSUE TITLE
HTML block working not as expected with \n

### ISSUE THREAD

**Issue by leduythuccs** [commonmark/commonmark-spec#680]
This 
```
<center>

`a`</center>
```

will become
```
<center>
<p><code>a</code></center></p>
```
Link: https://spec.commonmark.org/dingus/?text=%3Ccenter%3E%0A%0A%60a%60%3C%2Fcenter%3E%0A
![image](https://user-images.githubusercontent.com/23715841/121765225-9b2c9580-cb73-11eb-8626-4c20e7e81985.png)

But if I remove the \n in the second line:

```
<center>
`a`</center>
```
It will become

```
<center>
`a`</center>
```

Link: https://spec.commonmark.org/dingus/?text=%3Ccenter%3E%0A%60a%60%3C%2Fcenter%3E%0A
![image](https://user-images.githubusercontent.com/23715841/121765229-a384d080-cb73-11eb-91df-61829b66ea16.png)

More cases:
![image](https://user-images.githubusercontent.com/23715841/121765234-a8e21b00-cb73-11eb-991e-0cadf59784e2.png)
![image](https://user-images.githubusercontent.com/23715841/121765240-b13a5600-cb73-11eb-9777-15360ddfde4f.png)
![image](https://user-images.githubusercontent.com/23715841/121765241-b4354680-cb73-11eb-9f44-c5a85b7d502b.png)

**Comment by wooorm** [comment]
This behavior is documented in the spec: https://spec.commonmark.org/0.29/#html-blocks
