### ISSUE TITLE
Spoiler text

### ISSUE THREAD

**Issue by ValVoice** [commonmark/commonmark-spec#681]
You can add spoiler text on some flavors of Markdown, most notably Reddit and Discord.

# What is spoiler text?

Spoiler text is a span that requires clicking on to view the contents, intended for hiding spoilers.

![Spoiler text on Discord](https://user-images.githubusercontent.com/86004740/122510314-5eafdc80-d040-11eb-8439-acac8e4f9caa.png)

# Implementations in Markdown

Reddit writes spoiler text like this:

    Spoiler: >!Snape kills Dumbledore.!<

Discord writes spoiler text like this:

    Spoiler: ||Snape kills Dumbledore.||

**Comment by jgm** [comment]
See the extensive discussion of this on talk.commonmark.org.
