### ISSUE TITLE
Inconsistent behavior for inline html tags

### ISSUE THREAD

**Issue by meteorlxy** [commonmark/commonmark-spec#684]
We have some examples for raw html:

https://github.com/commonmark/commonmark-spec/blob/ab56f2eb275b671697cb9ee9e8277d26d759ed1e/spec.txt#L9006-L9030

Which shows that it is supported to split a html tag into multiple lines. However, there is an inconsitent behavior when spliting a `<img>` tag:

![image](https://user-images.githubusercontent.com/18205362/124481053-7629ec00-ddda-11eb-8148-69ee8070766e.png)

> [Reproduce link](https://spec.commonmark.org/dingus/?text=%3Cimg%20src%3D%22foo.png%22%3E%0A%0A%3Cimg%0Asrc%3D%22foo.png%22%3E%0A)

- When writing in a single line, it's recognized as a html block.
- When writing in multiple lines, it's recogized as inlined html.

I could find a related issue #492

**Comment by jgm** [comment]
This isn't inconsistent; it is just following the spec.
Have a look at the spec for raw HTML blocks.

Your first example is a type 7 HTML block.

Your second example is not an HTML block.  (Note that `img` isn't in the list for type 6.)
