### ISSUE TITLE
Inconsistency about blanks wrt list tightness

### ISSUE THREAD

**Issue by eureton** [commonmark/commonmark-spec#685]
The [definition](https://spec.commonmark.org/0.30/#blank-line) of `blank line` doesn't clarify scope:

> A line containing no characters, or a line containing only spaces (U+0020) or tabs (U+0009), is called a blank line.

In other words, it's not clear whether the line scope is the __document__ or the __surrounding block element__. Consider the snippet below:

``` markdown
- 
  abc
```

The latter interpretation classifies the line as blank wheres the former doesn't. 

Farther down, [Example 278](https://spec.commonmark.org/0.30/#example-278) complicates matters further because the prose assumes the latter interpretation:

> [...] some list items that start with a blank line but are not empty

whereas dingus implements the former (i.e. produced list is [marked _tight_](https://spec.commonmark.org/dingus/?text=-%0A%20%20foo%0A-%0A%20%20%60%60%60%0A%20%20bar%0A%20%20%60%60%60%0A-%0A%20%20%20%20%20%20baz%0A)).

Which of the two is correct?

**Comment by wooorm** [comment]
But like, extending your reasoning for seeing blank lines as ambiguous here to some other language in the spec, such as for headings, would also make `- # is this a heading?` “ambiguous”.

I’m not sure what language change you propose, but I’d say the fact that containers include “lines” is adequately explained in the respective sections on those containers themselves: [block quotes](https://spec.commonmark.org/0.30/#block-quotes), [list items](https://spec.commonmark.org/0.30/#list-items).

**Comment by eureton** [comment]
@wooorm I have proposed no change.

My post concludes with a question. What gets corrected (spec text or dingus implementation) depends on the answer, which I don't have.

**Comment by wooorm** [comment]
L1 in your example is *not* a blank line to the whole document. To the list item, it *is* a blank line.

I’m not seeing where the spec text and dingus are at odds with each other?

**Comment by eureton** [comment]
I see now where my confusion comes from. I was mistaking the scope implied by the tightness definition:

> A list is loose if any of its constituent list items are separated by blank lines

This makes

``` markdown
- abc
- 
  xyz
```

indeed tight, because L2 is blank to the item, but not to the list.
