### ISSUE TITLE
Add `loading="lazy"` attribute to all images by default

### ISSUE THREAD

**Issue by jimmywarting** [commonmark/commonmark-spec#705]
Specify so that images includes the lazy loading technic 
https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading

> "It's a way to shorten the length of the [critical rendering path](https://developer.mozilla.org/en-US/docs/Web/Performance/Critical_rendering_path), which translates into reduced page load times."

**Comment by jgm** [comment]
That's a rendering detail, so it doesn't concern the spec.
