### ISSUE TITLE
Clarification of the reason for right-flanking delimiter run's definition

### ISSUE THREAD

**Issue by ppwwyyxx** [commonmark/commonmark-spec#706]
Hi,

Forgive me if this is not the correct type of question to raise here.

I encountered the following rendering at https://markdown-it.github.io/ whose second line is unexpected to me: 
(left: markdown input; right: rendered markdown)
![2022-04-27_01-40](https://user-images.githubusercontent.com/1381301/165478305-b5f89dc6-2dca-4abb-aac1-8e3829988928.png)

After reading the definition of "right-flanking delimiter run" at https://spec.commonmark.org/0.29/#right-flanking-delimiter-run , it appears though that the above rendering is correct according to the spec.

However, I'm not able to understand why the definition is made this way so that the second line in my example should not be emphasized. I'd appreciate if anyone can answer this and mention it in the spec.

**Comment by jgm** [comment]
In the second line the second `**` run is (only) left-flanking, because it is preceded by punctuation and followed by a letter.

**Comment by ppwwyyxx** [comment]
Yes, I understand that the above rendering is correct according to the spec.

My question is "why the definition is made this way so that the second line in my example should not be emphasized". Or basically why the spec has such a rule. What cases does it mean to handle? These are not clear from the spec and is quite confusing given my example.

**Comment by jgm** [comment]
This isn't the place to discuss that, nor do I have time right now. You can raise it in the forum if you like.

**Comment by jgm** [comment]
PS. I agree that this is a bad result, intuitively. The question is how to design a comprehensive set of rules that gets the "right" result in this case without bad results elsewhere. The current rules are based on a lot of experience and experimentation, and I'm open to the idea that there may be better ones, but looking at individual rules piecemeal is not going to be revealing.

**Comment by jgm** [comment]
An easy way to experiment is to change the code and then see which test cases fail.
