### ISSUE TITLE
(Intentional?) inconsistency between 4.6 block HTML and 6.6 raw HTML comments

### ISSUE THREAD

**Issue by wooorm** [commonmark/commonmark-spec#712]
The block HTML algorithm here allows `<!-->`, `<!--->`, etc, as comments.
These comments are also fine by the HTML parser ([13.2.5.44, case for `U+002D`](https://html.spec.whatwg.org/multipage/parsing.html#comment-start-dash-state)).
(note there are a couple of cases such as `<!>` and `<!->` which HTML also allows but sees as parse errors, I am not talking about these).

The “inline” algorithm here does not allow `<!-->` or `<!--->`. They look *a lot* like comments, so I don’t really expect people to depend on these characters to be text. And it’s inconsistent with blocks. Can we change the spec to allow them?

I can do the work

**Comment by wooorm** [comment]
Good to hear! One thing that I was wondering: `--` in a comment is the same. For example, `<!-- some stuff -- some more stuff -->`. OK too?

**Comment by jgm** [comment]
If I recall, we deliberately simplified the comment parsing (even though this diverts from HTML standard).  I don't remember why, though.  I'm okay with implementing something more standard as long as it doesn't increase complexity too much, both in the spec and in parsers.

**Comment by wooorm** [comment]
I wouldn’t know why that was the case! Perhaps if you care more about XML than HTML?

In my case, this just removes states in my state machine that are needed for inline, but not for block.
I can see `--` in comments being used by humans, so that might even be considered a bug fix.

**Comment by jgm** [comment]
For reference, the HTML5 spec for comments:
https://html.spec.whatwg.org/multipage/syntax.html#comments

**Comment by wooorm** [comment]
Thanks for merging this, John!

**Comment by jgm** [comment]
Reopening until we get the issue of `<!-->` and `<!--->` (not to mention `<!-- hi -->`) sorted out.  See comments on linked PR.

**Comment by jgm** [comment]
I think an inconsistency between the block and inline cases is okay, given that the spec for block HTML allows invalid HTML.

**Comment by jgm** [comment]
However, allowing `--` inside HTML comments is a change worth making.

**Comment by wooorm** [comment]
commented in the PR: https://github.com/commonmark/commonmark-spec/pull/713#issuecomment-1241059993.
