### ISSUE TITLE
the definition of "line" should precede its usage in the spec?

### ISSUE THREAD

**Issue by greggman** [commonmark/commonmark-spec#721]
I'm new to this spec and probably missing things but, starting from the top down I see section 2.1

> A [line](https://spec.commonmark.org/0.30/#line) is a sequence of zero or more [characters](https://spec.commonmark.org/0.30/#character) other than line feed (U+000A) or carriage return (U+000D), followed by a [line ending](https://spec.commonmark.org/0.30/#line-ending) or by the end of file.

Then I get to 4.1

> ## 4.1 Thematic breaks
>
> A line consisting of optionally up to three spaces of indentation, followed by a sequence of three or more matching `-`, `_`, or `*` characters, each followed optionally by any number of spaces or tabs, forms a [thematic break](https://spec.commonmark.org/0.30/#thematic-break).
>
> ...
>
> Four spaces of indentation is too many...

So then I go test this markdown

```
* foo
   * foo
 
     ***
```

That `***` has more than 3 spaces so fails the rules just specified. My guess is that the actual definition of `line` in 4.1 is supposed to include trimming the current block's indentiation level? Maybe that gets covered elsewhere but it seemed worth mentioning that 4.1 seems to be relying on what at least until that point is unspecified behavior.

**Comment by wooorm** [comment]
You're putting things in lists. Lists are covered later. I'd think that it makes sense that when you use constructs explained later, those constructs can interfere with earlier explanations?

**Comment by greggman** [comment]
Most specs I've read would not bury exceptions to their defintions deep in the spec.

Also, having just read through the list section I'm not seeing where the definition of line in 2.1 and 4.1 is upadted

Note the same issue happens with block quotes

```
> foo
>
> ***
```

That `> ***` does not fit the defintion from 4.1 and 2.1

**Comment by jgm** [comment]
There's a basic sufficient condition for a thematic break, which you quoted.  And then the block quote spec says: if you have a sequence of lines that constitute an X, and you prepend `> ` to each line, then you have a block quote whose contents are an X.

Together these rules imply that

```
> ***
```
is a thematic break inside a block quote. Hope that helps.

**Comment by jgm** [comment]
It's just not true that thematic break gets "redefined" later. Think of the spec as an inductive definition with base cases for the leaf elements and an inductive clause for the containers.

**Comment by Crissov** [comment]
I agree that the term _line_ is currently used with two or maybe even three meanings in the specification. The second and the third are hardly distinguished:

1. A _code line_ beginning at start of file or immediately after a line ending as specified in 2.1. Note that the prose there currently does not say where a line starts, only where it ends and what it may contain. 
2. A _content line_ which is a code line stripped of any block markers and inherited indentation from the preceding code line, but including its own line prefix and added indentation before and after it as well as the optional line suffix in ATX headings. 
3. A _text line_ is a trimmed content line with all prefixes and suffixes and trailing whitespace removed. Maybe this includes collapsing soft line breaks and joining consecutive content lines of the same block.

**Comment by wooorm** [comment]
Section 2.1 is one of the first parts of the spec. It’s a preliminary on how character (groups) are called, which are used later in the spec. What is a character? What’s whitespace or punctuation?

One such character group is zero or more characters that are not line endings: a line.
As @Crissov notes, there’s nothing in the phrasing that indicates a line must start after a line ending in the whole document or at the beginning of the whole document.
The idea that the term `line` is equivalent to `line = wholeDocument.split('\n')[0]` does not match what’s written in the spec.

> There's a common definition of "line" pretty much every programmer assumes.

I don’t really subscribe to the idea that “everyone” thinks that that is what lines are. And if so, the section 2.1 explains that term is used in the spec as a sequence of characters.  If you missed 2.1, we could link to it from 4.1.

> Anyway, I'm not here to argue.

To me, your comments come across as the inverse of this. You’re using hand-wavy terms of “every programmer assumes”, “all their careers, hobbies, classes”. Things like “Just remember”, “You can take it or leave it”, all paint a picture of “you and everyone are right”, while the tiny group of people who work on this are completely wrong.

I also haven’t heard any practical improvement you suggest?

**Comment by greggman** [comment]
> To me, your comments come across as the inverse of this. You’re using hand-wavy terms of “every programmer assumes”, “all their careers, hobbies, classes”. Things like “Just remember”, “You can take it or leave it”, all paint a picture of “you and everyone are right”, while the tiny group of people who work on this are completely wrong.

That's a very uncharitable view. I said it's an opinion. My opinion is correct for me. If I say this liquorice candy tastes bad to me and you say it tastes great I'm not telling you you are wrong. But, I am not wrong either as it applies to me. If I stay something is hard to understand for me, that's truth for me, whether or not it's a truth of you. So the comment of take it or leave it is "this is my point of view, it confused me, my experience suggests it will confuse others."

To me the spec is confusing because I've parsed 1000s of files before and I've written code like

    lines = content.split('\n')
    for (line of lines) {
       ...

2.1 doesn't tell me that the variable `line` in that code snippet is wrong so I could easily write that code and then only later find out. Oh, that's not what they mean by "line". The `line` in the code above is really some kind of meta line

    metaLines = content.split('\n')
    for (metaLine of metaLines) {
       line = extractLineFromMetaLine(metaLine)

Concretely, in my opinion it would be better to make that clear in 2.1.

> [line](https://spec.commonmark.org/0.30/#line) is a sequence of zero or more [characters](https://spec.commonmark.org/0.30/#character) other than line feed (U+000A) or carriage return (U+000D),  followed by a [line ending](https://spec.commonmark.org/0.30/#line-ending) or by the end of file. A line does not nessesarily start after a line ending as it may be proceeded by various block constructions.

Or something to that effect.

Now I immediately know this defintion is different than the concept of line in just about [every example of "lines of a string" ever written](https://www.google.com/search?q=separating+a+string+into+lines). That seems like it would confuse less people even is less = 1, me.
