### ISSUE TITLE
break list of same type into separate lists

### ISSUE THREAD

**Issue by ddormer** [commonmark/commonmark-spec#725]
Currently the [CommonMark spec](https://spec.commonmark.org/0.30/#example-308) suggests using a blank HTML comment to break apart lists, for example:
```
- one
- two

<!-- -->

- one
```

The problem is, that this is only a solution when rendering to HTML; From what I can see there are no alternatives in the event that your render target doesn't support empty comments or in the event you want to render into multiple formats.

My specific use case is using commonmark.js to render Markdown into BBCode (gasp!) where comments are not available.

Would treating two consecutive newlines as the end of a list be an option or does that breakdown in other examples? Or perhaps the empty comment could be made explicit syntax and excluded from being rendered while also still the lists?

**Comment by wooorm** [comment]
You can use different markers:

```markdown
- one
- two

* one
```

Two blank lines was I believe explicitly not supported in CommonMark, and there should be prose in the spec about it.

**Comment by jgm** [comment]
> The problem is, that this is only a solution when rendering to HTML

That's not so.  The *parser* has to recognize the HTML comment, which it should because it is part of the spec.

It matters not whether the *renderer* does anything with this HTML comment; if it has null output, that's fine!
