### ISSUE TITLE
Example 333 actually strips nothing

### ISSUE THREAD

**Issue by rhysd** [commonmark/commonmark-spec#753]
[Example 333](https://spec.commonmark.org/0.30/#example-333):

`````````````````````````````````
Only [spaces], and not [unicode whitespace] in general, are
stripped in this way:

```````````````````````````````` example
` b `
.
<p><code> b </code></p>
````````````````````````````````
`````````````````````````````````

If the description is correct, spaces around 'b' must be stripped as `<p><code>b</code></p>`. But the example is not stripped actually.

On GitHub, these spaces are actually stripped. `` ` b ` `` is ` b ` as rendered here.

**Comment by wooorm** [comment]
Those characters are not spaces but U+00A0 (No-Break Space, NBSP). The line above explains it: only the actual ASCII space (U+0020) is removed in this case.

See:

`` ` b ` `` -> ` b `

`` ` b ` `` -> ` b `

Note that copy/pasting things might loose these characters

**Comment by rhysd** [comment]
Ah, I see. I misunderstood that nbsp is included in the 'spaces' in CommonMark. Thank you for clarifying that.
