### ISSUE TITLE
Wiki page Markdown-Flavors vandalized?

### ISSUE THREAD

**Issue by tomhundt** [commonmark/commonmark-spec#764]
This page appears to have been basically wiped out, either deliberately or accidentally:
<https://github.com/commonmark/commonmark-spec/wiki/Markdown-Flavors>

Not just the content but also the footer, which is just plain weird (and apparently has been, per its history).  The footer is shared among the entire repo's Wiki pages.

Apologies if this is actually all intentional and I just don't "get it".

Thanks

**Comment by jgm** [comment]
thanks for letting us know!  It's not intentional.

**Comment by jgm** [comment]
Reverted the changes and banned the vandal.
