### ISSUE TITLE
Spec is confusing on type 7 HTML Blocks

### ISSUE THREAD

**Issue by toptensoftware** [commonmark/commonmark-spec#780]
For the start condition of a type 7 HTML block the spec says:

> line begins with a complete [open tag](https://spec.commonmark.org/0.31.2/#open-tag)

At various points the spec for an open-tag says they can contain:

> and up to one line ending.

I was reading this as if a type 7 HTML block can start with an open tag that contains line breaks - but in fact they can't.

Perhaps the start condition should be worded as "line begins with _and contains_ a complete open-tag", or more explicitly state that the "up to one line ending" doesn't apply for type 7 blocks.

**Comment by Annastaciahubbard** [comment]
Your above suggestion / explanation has worked for me in the past

**Comment by wooorm** [comment]
Some sort of “line begins with *and contains* a complete open-tag” seems good to me

**Comment by jgm** [comment]
The word "complete" was meant to do the work.  But I'm happy to change it as suggested.

**Comment by jgm** [comment]
Pushing back a little:  the current text does say:  "begins with a complete open tag...**all on a single line**".  Isn't that sufficiently explicit?

**Comment by jgm** [comment]
Note: "all on a single line" was added in 800e199b0df62c64b8eaee9a5996a5da6d2bf8bf and is not in the most recent release!  I guess someone else had exactly the same problem you did.  Isn't the fix sufficient?

**Comment by toptensoftware** [comment]
> The word "complete" was meant to do the work

Yes, but "starts with a complete" makes it confusing - hence my suggestion of "starts with and contains".

> Note: "all on a single line" was added

I was going off what's [written here](https://spec.commonmark.org/0.31.2/#html-blocks) so didn't see the 'all on a single line' change.

That covers it, but I still think confusing because it reads like: "a line that starts with an opening tag which can contain new lines but all on one line".  

Personally, I think it warrants an explicit comment to make this clear.
