### ISSUE TITLE
Wiki - List of CommonMark Implementations page incomplete

### ISSUE THREAD

**Issue by mikolfaro** [commonmark/commonmark-spec#785]
The [third party implementation](https://github.com/commonmark/commonmark-spec/wiki/List-of-CommonMark-Implementations) page does not list other plugins anymore.

[Previous version](https://github.com/commonmark/commonmark-spec/wiki/List-of-CommonMark-Implementations/caacff5fc3aa937a74a32a1fd6f2df6e6c1a8f7e) had a more complete list.

**Comment by jgm** [comment]
Evidently someone vandalized the page. Thanks.
I can roll it back.
